import Head from "next/head";
import Image from "next/image";
import Navbar from "@component/navbar";
import styles from "../styles/index.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xilflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className="wrapperBox">
        <div className="container">
          <div className="row">
            <div className="col">
              <div className="garis-atas">Haloo...,Welcome In Xilflix</div>
              <h1 className="h1-profesi">Movie</h1>
              <h1 className="h1-profesi profesi-back">Popular</h1>
              <h3 className="h3-profesidepan">
                Movie <br />
                <span className="span-back">Popular</span>
              </h3>
              <hr className="garisbawah1" />
              <hr className="garisbawah2" />
              <hr className="garisbawah3" />
            </div>
            <div className="col">
              <div className="wrapperCarousel">
                <img src="https://image.tmdb.org/t/p/w500//ejXBuNLvK4kZ7YcqeKqUWnCxdJq.jpg" />
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col text-center">
              <h4 className={styles.th4}>Created by WildanIcube#3</h4>
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        .wrapperBox {
          width: 100%;
          background-color: black;
          min-height: 100%;
        }
        .garis-atas {
          height: 25px;
          font-size: 23px;
          color: #8c8c8c;
          font-family: "Aquirebiasa";
          margin-top: 130px;
        }
        .h1-profesi {
          font-size: 100px;
          margin-left: 10px;
          color: #332100;
          letter-spacing: 2px;
          font-family: "Aquire";
        }
        .profesi-back {
          margin-top: -40px;
          margin-left: 15px;
          color: #262626;
        }
        .h3-profesidepan {
          font-family: "Aquirebiasa";
          font-size: 67px;
          margin-top: -173px;
          color: #ffaf1a;
        }
        .span-back {
          color: white;
        }
        .garisbawah1 {
          border-color: orange;
          width: 5%;
          float: left;
          margin-left: 80px;
          margin-top: -5px;
        }
        .garisbawah2 {
          border-color: orange;
          width: 10%;
          float: left;
          margin-left: 10px;
          margin-top: -5px;
        }
        .garisbawah3 {
          border-color: orange;
          width: 20%;
          float: left;
          margin-left: 10px;
          margin-top: -5px;
        }
        .wrapperCarousel {
          background-color: white;
          border-radius: 20px;
          box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;
          width: 400px;
          height: 400px;
          margin-top: 60px;
          margin-left: 150px;
        }
        .wrapperCarousel img {
          border-radius: 20px 0px 0px 20px;
          witdh: 500px;
          height: 400px;
        }
      `}</style>
    </div>
  );
}
